version: '3.9'
services:
  stablediffusion-infinity:
    build: .
    ports:
    - 8888:8888
    volumes:
      - ./checkpoints/:/app/checkpoints
      - ./dataset/:/app/dataset
      - ./img/:/app/img
      - ./notebooks/:/app/notebooks
      - ./src/:/app/src

    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]